export interface EntryPerDayOfTheMonth {
    title?: string;
    day?: number;
    year: number;
    january?: number;
    february?: number;
    march?: number;
    april?: number;
    may?: number;
    june?: number;
    july?: number;
    august?: number;
    september?: number;
    october?: number;
    november?: number;
    december?: number;
    januaryId?: number;
    februaryId?: number;
    marchId?: number;
    aprilId?: number;
    mayId?: number;
    juneId?: number;
    julyId?: number;
    augustId?: number;
    septemberId?: number;
    octoberId?: number;
    novemberId?: number;
    decemberId?: number;
}